# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-20 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturemap2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='legacy_pk',
        ),
    ]
