# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-23 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturemap2', '0002_remove_family_legacy_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'families'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
        migrations.RemoveField(
            model_name='source',
            name='display_in_directory_ind',
        ),
        migrations.RemoveField(
            model_name='source',
            name='full_search_ind',
        ),
        migrations.RemoveField(
            model_name='source',
            name='vouchered_ind',
        ),
        migrations.RemoveField(
            model_name='species',
            name='auth_name_ind',
        ),
        migrations.RemoveField(
            model_name='species',
            name='currency_ind',
        ),
        migrations.RemoveField(
            model_name='species',
            name='naturalised_flag',
        ),
        migrations.RemoveField(
            model_name='specieslocation',
            name='hide_ind',
        ),
        migrations.AddField(
            model_name='source',
            name='display_in_directory',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='source',
            name='full_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='source',
            name='vouchered',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='species',
            name='auth_name',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='species',
            name='currency',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='species',
            name='naturalised',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='specieslocation',
            name='hide',
            field=models.NullBooleanField(default=None),
        ),
    ]
