# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-24 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naturemap2', '0005_remove_source_core_dataset_ind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='naturemap2.Source'),
        ),
    ]
