# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-25 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naturemap2', '0006_auto_20200324_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='specieslocation',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieslocation',
            name='site_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='specieslocation',
            name='site_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='naturemap2.Source'),
        ),
    ]
