# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-26 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturemap2', '0007_auto_20200326_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='supra_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='supra_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
