# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-26 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturemap2', '0008_auto_20200326_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='kingdom_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='kingdom_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
