# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-26 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturemap2', '0009_auto_20200326_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='specieslocation',
            name='document',
            field=models.TextField(blank=True, null=True),
        ),
    ]
