# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-26 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturemap2', '0010_specieslocation_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='specieslocation',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
