# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-26 07:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturemap2', '0011_specieslocation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specieslocation',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
