# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-27 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturemap2', '0012_specieslocation_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='classname',
            new_name='class_name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='species',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='species',
            name='supra',
        ),
        migrations.RemoveField(
            model_name='specieslocation',
            name='site',
        ),
    ]
