# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-28 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naturemap2', '0014_auto_20200330_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='class_name',
            field=models.CharField(blank=True, help_text='The taxonomic class this family belongs to', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='division',
            field=models.CharField(blank=True, help_text='The taxonomic division this family belongs to', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='kingdom_description',
            field=models.CharField(blank=True, help_text='A description of this kingdom', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='kingdom_name',
            field=models.CharField(blank=True, help_text='The name of this kingdom', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(help_text='Name of family', max_length=64),
        ),
        migrations.AlterField(
            model_name='family',
            name='order',
            field=models.CharField(blank=True, help_text='The taxonomic order this family belongs to', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='sup_code',
            field=models.CharField(help_text='Supra-group code', max_length=16),
        ),
        migrations.AlterField(
            model_name='source',
            name='code',
            field=models.CharField(help_text='The unique code for this source', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='custodian',
            field=models.CharField(blank=True, help_text='The effective custodian of this data source', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, help_text='A more fullsome description of the source', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_processed_on',
            field=models.DateField(blank=True, help_text='The date the datasource ws last processed and updated in NatureMap', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_updated_on',
            field=models.DateField(blank=True, help_text='The date this datasource was last updated or modified by the custodian', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(blank=True, help_text='Documents the source type eg species names, attribute values', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(blank=True, help_text='A brief title for the data source - appears in the web-page drop-down list', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, help_text='The URL for metadata describing this source. It may be used as an alternative to displaying local metadata.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='author',
            field=models.CharField(blank=True, help_text='The author of this taxon', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='consv_code',
            field=models.CharField(blank=True, help_text='The conservation code for this taxon, if known.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='currency',
            field=models.BooleanField(default=True, help_text='A flag indicating whether this name is current.'),
        ),
        migrations.AlterField(
            model_name='species',
            name='family',
            field=models.ForeignKey(help_text='The family this species belongs to', on_delete=django.db.models.deletion.PROTECT, to='naturemap2.Family'),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.CharField(help_text="The species' genus", max_length=128),
        ),
        migrations.AlterField(
            model_name='species',
            name='informal',
            field=models.CharField(blank=True, help_text='Flag indicating whether this is a published name', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='infraspecies_name',
            field=models.CharField(blank=True, help_text='Infraspecific name', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='infraspecies_rank',
            field=models.CharField(blank=True, help_text='The infraspecific rank of this taxon', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(help_text='A concatenation of genus, species, rank and infra name', max_length=256),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_id',
            field=models.IntegerField(blank=True, help_text='The original authoritative name_id of this name. If not null this number must be unique across all records.', null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='naturalised',
            field=models.NullBooleanField(default=None, help_text='Flag indicating whether this taxon has been introduced into WA'),
        ),
        migrations.AlterField(
            model_name='species',
            name='source',
            field=models.ForeignKey(help_text='The source of this name eg WACENSUS', on_delete=django.db.models.deletion.PROTECT, to='naturemap2.Source'),
        ),
        migrations.AlterField(
            model_name='species',
            name='species',
            field=models.CharField(help_text='The specific epithet for this taxon', max_length=128),
        ),
        migrations.AlterField(
            model_name='species',
            name='supra_code',
            field=models.CharField(blank=True, db_index=True, help_text='Supra-group code', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='supra_name',
            field=models.CharField(blank=True, help_text='Description of supra-group', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='vernacular',
            field=models.CharField(blank=True, help_text='The common name for this taxon', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specieslocation',
            name='accuracy',
            field=models.IntegerField(blank=True, help_text='The spatial accuracy of the point (metres)', null=True),
        ),
        migrations.AlterField(
            model_name='specieslocation',
            name='site_name',
            field=models.CharField(blank=True, help_text='The name of the site, if it has one', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='specieslocation',
            name='site_source',
            field=models.ForeignKey(blank=True, help_text='The source of this site information', null=True, on_delete=django.db.models.deletion.PROTECT, to='naturemap2.Source'),
        ),
    ]
